### ISSUE TITLE
What about docker-compose.local.yml?

### ISSUE THREAD

**Issue by Petemir** [Daursu/laradocker#2]
Hello, first of all, thank you very much for your detailed tutorial, it is really great.

Having said that, I have some doubts regarding the file docker-compose.local.yml. In the "[Local Configuration -> docker-compose.yml](https://www.laradocker.com/local-configuration/#docker-compose-yml)" section of the tutorial, you say "[...] and another one called docker-compose.local.yml". Yet, that file is never created, just docker-compose.override.yml . 

Following the guide, then, at the moment of executing ```docker-compose up```, I receive the following complaint:
```ERROR: Service 'php' depends on service 'composer' which is undefined.```
The composer service is defined in docker-compose.local.yml (from what I gather from the repo), which is never created through the tutorial, but not in the created docker-compose.override.yml. 

Also, maybe adding that you can select the files plus overrides with ```-f``` parameter could be a plus.

I hope I was clear... thanks!

**Comment by Daursu** [comment]
Thanks, I've updated the guide. The `docker-compose.override.yml` contains the composer service as well.

**Comment by Petemir** [comment]
Perfect, thank you once again.

**Comment by Petemir** [comment]
Sorry to bug you again, but just FYI, now the repo doesn't reflect what it's on the site.
